### ISSUE TITLE
who to use FaceDetector full range on gpu？

### ISSUE THREAD

**Issue by RichardQin1** [google-ai-edge/mediapipe#5572] opened 2024-08-16 05:40 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

linux ubuntu22.04

### MediaPipe Tasks SDK version

0.10.11

### Task name (e.g. Image classification, Gesture recognition etc.)

FaceDetector

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

full range on gpu

### Describe the expected behaviour

full range on gpu

### Standalone code/steps you may have used to try to get what you need

```shell
old version python use code：

import cv2
import mediapipe as mp

mp_face_detection = mp.solutions.face_detection
face_detection = mp_face_detection.FaceDetection(min_detection_confidence=0.5, model_selection=1)
mp_drawing = mp.solutions.drawing_utils
cap = cv2.VideoCapture(video_path)
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    results = face_detection.process(frame_rgb)
```
new code:
```
import cv2
import mediapipe as mp
import numpy as np
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

BaseOptions = mp.tasks.BaseOptions
FaceDetector = mp.tasks.vision.FaceDetector
FaceDetectorOptions = mp.tasks.vision.FaceDetectorOptions
VisionRunningMode = mp.tasks.vision.RunningMode
mp_drawing = mp.solutions.drawing_utils
options = FaceDetectorOptions(
    base_options=BaseOptions(model_asset_path='blaze_face_short_range.tflite',
                             delegate=python.BaseOptions.Delegate.GPU),
    running_mode=VisionRunningMode.VIDEO)
cap = cv2.VideoCapture(video_path)
with FaceDetector.create_from_options(options) as detector:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=np.asarray(frame))
        face_detector_result = detector.detect_for_video(mp_image, int(t_time))
```
```


### Other info / Complete Logs

_No response_

**Comment by kuaashish** [comment] 2024-08-16 06:44
Hi @RichardQin1,

We are closing this issue as it is a duplicate of a recently raised issue: https://github.com/google-ai-edge/mediapipe/issues/5573. Please follow that issue, which we are already tracking.

Thank you!!

**Closed by kuaashish** 2024-08-16 06:44 UTC
Labels: status:duplicate, gpu, platform:python, task:face detection, os:linux-non-arm
