### ISSUE TITLE
When will the Mac fix for worker threads be released? (PR 5636 already merged on main)

### ISSUE THREAD

**Issue by joacopaz** [google-ai-edge/mediapipe#5710] opened 2024-10-30 17:47 UTC
### MediaPipe Solution (you are using)

latest

### Programming language

typescript

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

Mac browsers crash on worker threads because of a Mac identification util bug

### Will this change the current API? How?

Fix already merged #5636 just want to know when it's coming out on release

### Who will benefit with this feature?

Every mac worker thread mediapipe browser user

### Please specify the use cases for this feature

Mac worker threads on browser crashes, we want to use worker threads to optimize separation of concerns of process and memory

**Comment by schmidt-sebastian** [comment] 2024-10-31 16:42
We are currently working on a release.

**Comment by kuaashish** [comment] 2024-11-04 08:53
Hi @joacopaz,

As mentioned [above](https://github.com/google-ai-edge/mediapipe/issues/5710#issuecomment-2450341434), we are working on the release, which will be available soon. The PyPi release has already been completed and can be viewed [here](https://pypi.org/project/mediapipe/). However, we cannot provide an exact date for release on other platforms at this time.

Thank you!!

**Comment by kuaashish** [comment] 2024-11-05 08:44
Hi @joacopaz,

We have released a new version on NPM ([v0.10.18](https://www.npmjs.com/package/@mediapipe/tasks-vision?activeTab=readme)) that includes the fix. You can check it out here and let us know if it resolves the issue. Please note that the GitHub release notes for v0.10.18 are still pending publication.

Thank you!!

**Comment by kuaashish** [comment] 2024-11-06 08:58
Hi @joacopaz,

Please update your feedback, If the issue is resolved in the latest version, we can mark it as complete and close the status.

Thank you!!

**Closed** 2024-11-08 18:20 UTC
Labels: type:feature, platform:ios, stat:awaiting response, platform:javascript, os:macOS

**Comment by joacopaz** [comment] 2024-11-19 18:34
This issue has been fixed in the latest version! Thanks team
