### ISSUE TITLE
PermissionError: [Errno 13] Permission denied on Windows

### ISSUE THREAD

**Issue by SamedHrmn** [google-ai-edge/mediapipe#5761] opened 2024-12-01 19:58 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10 

### Python Version

3.10

### MediaPipe Model Maker version

0.2.1.4

### Task name (e.g. Image classification, Gesture recognition etc.)

Face stylization

### Describe the actual behavior

Model wasnt initializing

### Describe the expected behaviour

Model creating succesfully

### Standalone code/steps you may have used to try to get what you need

Hi, Im trying to make retrain model using face-stylization guide here,  https://ai.google.dev/edge/mediapipe/solutions/customization/face_stylizer

**Comment by kuaashish** [comment] 2024-12-02 09:27
Hi @SamedHrmn,

We are closing this issue as Duplicate of #5762, Please follow up that issue for further updates.

Thank you!!

**Closed by kuaashish** 2024-12-02 09:27 UTC
Labels: status:duplicate, os:windows, platform:python, type:modelmaker, task: face stylizer
