### ISSUE TITLE
invalid registered toolchain '@local_execution_config_python//:py_toolchain'

### ISSUE THREAD

**Issue by yourj4m** [google-ai-edge/mediapipe#5661] opened 2024-10-02 21:00 UTC
### OS Platform and Distribution

Ubuntu 24.04.1 LTS

### Programming Language and version

C++ 13.2.0

### Bazel version

Bazelisk version: v1.22.0, Build label: 6.1.1

### Android AAR (if android)

None

### Describe the problem

I am following the tutorial here: [link](https://ai.google.dev/edge/mediapipe/framework/getting_started/install.md#installing_on_debian_and_ubuntu) \
and always run into the same error (see below) when running 
```bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world``` 

I have already tried all options listed under step 3. \
Python is most certainly installed. I have also tried adding the ```--action_env PYTHON_BIN_PATH="/usr/bin/python3.12"```
flag, to no avail..

### Complete Logs

```shell
ERROR: /home/xxx/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:10: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: invalid registered toolchain '@local_execution_config_python//:py_toolchain': error loading package '@local_execution_config_python//': Unable to find package for @python//:defs.bzl: The repository '@python' could not be resolved: Repository '@python' is not defined.
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: 
INFO: Elapsed time: 23.003s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (28 packages loaded, 10 targets co\
nfigured)
    currently loading: @local_execution_config_python// ... (13 packages)
ERROR: Build failed. Not running target
```

**Comment by kuaashish** [comment] 2024-10-03 09:35
Hi @yourj4m,

It seems there might be an issue with the Python version. Could you try using a version between 3.9 and 3.11? Please let us know if the issue still persists.

Thank you!!

**Comment by yourj4m** [comment] 2024-10-03 13:58
Hey, thanks for the quick response !

I installed python 3.9 using 
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.6
```
And then ran 
```
bazel run --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="/usr/bin/python3.9" mediapipe/examples/desktop/hello_world:hello_world
```
which sadly led to the same output of 
```
INFO: Build option --action_env has changed, discarding analysis cache.
ERROR: /home/jonas/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:10: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: invalid registered toolchain '@local_execution_config_python//:py_toolchain': error loading package '@local_execution_config_python//': Unable to find package for @python//:defs.bzl: The repository '@python' could not be resolved: Repository '@python' is not defined.
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: 
INFO: Elapsed time: 0.487s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 10 targets co\
nfigured)
    currently loading: @local_execution_config_python// ... (29 packages)
ERROR: Build failed. Not running target
```
I also tried again after running `bazel clean --expunge`, which didn't help...

**Comment by reljai** [comment] 2024-10-04 18:52
I also hit the same issue. Going back to previous commits it appears to be caused by https://github.com/google-ai-edge/mediapipe/commit/7a9d25df0b32ff2fbc17b5ff474b5c7778bd1976 which no longer calls python_register_toolchains.

**Comment by lwcode** [comment] 2024-10-06 10:49
me too, I have the same issue, I met this problem with the demo "/mediapipe/examples/coral" use docker, I have tried different linux version(debian:buster with python3.7, debian:bullseye with python3.9) but problem is the same.

**Comment by DerAndereJohannes** [comment] 2024-10-07 10:23
I have the same issue and have tried with python versions from 3.7 to 3.11. Running on WSL Ubuntu 22.04.5 LTS.

**Comment by jorgen-17** [comment] 2024-10-07 14:55
same for me on MacOs (Python 3.11.4) and also saw the same issue when I tried to run via Docker

**Comment by reljai** [comment] 2024-10-07 15:35
I tried running with --action_env PYTHON_BIN_PATH=$(which python3) but that did not help. I just ended up checking out the last released version (v0.10.15) which unblocks for now.

**Comment by pbonazzi** [comment] 2024-10-08 09:24
I have got the same issue with Python 3.10

**Comment by pbonazzi** [comment] 2024-10-08 10:12
It works if I use a previous commit.

```
git checkout 7c625938d8074b77e6cefcc29beabd995c613e2b
```

**Comment by anupamkaul** [comment] 2024-10-08 22:10
In 'git checkout 7c625938d8074b77e6cefcc29beabd995c613e2b' what repo's SHA is referred to?

**Comment by schmidt-sebastian** [comment] 2024-10-09 16:35
I am working on upgrading our build to use TF's hermetic Python. Unfortunately, we had to upgrade our dependency on TF before this was quite ready.

You can unblock yourself by including a patch such as:

diff --git a/WORKSPACE b/WORKSPACE
index de65a5098..f02edfe82 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -66,8 +66,9 @@ http_archive(
     url = "https://github.com/bazelbuild/rules_python/releases/download/0.26.0/rules_python-0.26.0.tar.gz",
 )
 
-load("@rules_python//python:repositories.bzl", "py_repositories")
+load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")
 py_repositories()
+python_register_toolchains("python", ignore_root_user_error = True, python_version = "3.12")
 
 load("@rules_python//python:pip.bzl", "pip_parse")
 pip_parse(

**Comment by pbonazzi** [comment] 2024-10-10 13:54
> In 'git checkout [7c62593](https://github.com/google-ai-edge/mediapipe/commit/7c625938d8074b77e6cefcc29beabd995c613e2b)' what repo's SHA is referred to?

this repo.

**Comment by schmidt-sebastian** [comment] 2024-10-10 18:48
Fixed by https://github.com/google-ai-edge/mediapipe/commit/51248f5a920d12d7870dfa31de54b467e8cf62f0

**Closed by schmidt-sebastian** 2024-10-10 18:48 UTC
Labels: type:build/install, platform:c++, os:linux-non-arm

**Comment by anupamkaul** [comment] 2024-10-10 23:37
works now, thanks
