### ISSUE TITLE
Minimum configuration requirements to run mediapipe in Web, Android, iOS.

### ISSUE THREAD

**Issue by JhansiPyla28** [google-ai-edge/mediapipe#5497] opened 2024-06-21 12:09 UTC
### Description of issue (what needs changing)

Device specifications for mediapipe to run on Web, Android and iOS

### Clear description

I am looking for the minimum configuration requirements to run MediaPipe effectively on Android, iOS, and Web devices. Could you please provide details on the following for each platform?  Hardware Specifications:  CPU (cores, clock speed) RAM Storage GPU (specific brands or models, if any) Software Specifications:  Minimum OS version Required dependencies or libraries Minimum browser versions for Web Additional Information:  Performance benchmarks, if available Optimization recommendations for lower-end devices Thank you!

**Comment by kuaashish** [comment] 2024-06-24 09:08
Hi @JhansiPyla28,

Please allow us some time to discuss with our team. We will update you on the status. For now, we are closing this issue as a duplicate of #5498 and will provide updates through that issue.

**Closed** 2024-06-24 09:08 UTC
Labels: type:performance
